import React from 'react';
import Checkbox from '@material-ui/core/Checkbox';
import RedditTextField from './RedditTextField';
import Autocomplete from '@material-ui/lab/Autocomplete';
import CheckBoxOutlineBlankIcon from '@material-ui/icons/CheckBoxOutlineBlank';
import CheckBoxIcon from '@material-ui/icons/CheckBox';

const icon = <CheckBoxOutlineBlankIcon fontSize="small" />;
const checkedIcon = <CheckBoxIcon fontSize="small" />;

export default function LocationCheckboxes(props) {
  const handleChange = (event, newValue) => {
    props.updateChange(newValue)
  };
  return (
    <Autocomplete
      multiple
      id="location-checkboxes"
      options={listOfCountries}
      getOptionLabel={(option) => option.name}
      renderOption={(option, { selected }) => (
        <React.Fragment>
          <Checkbox
            icon={icon}
            checkedIcon={checkedIcon}
            style={{ marginRight: 8 }}
            checked={selected}
          />
          {option.name}
        </React.Fragment>
      )}
      style={{ width: 500 }}
      renderInput={(params) => (
        <RedditTextField {...params} variant="filled" label="Country"/>
      )}
      onChange={handleChange}
    />
  );
}


const listOfCountries = [ 
  {name: 'World Wide'},
  {name: 'Afghanistan'},
  {name: 'Albania'},
  {name: 'Algeria'},
  {name: 'American Samoa'},
  {name: 'Andorra'},
  {name: 'Angola'},
  {name: 'Antarctica'},
  {name: 'Argentina'},
  {name: 'Armenia'},
  {name: 'Aruba'},
  {name: 'Australia'},
  {name: 'Austria'},
  {name: 'Azerbaijan'},
  {name: 'Bahamas'},
  {name: 'Bahrain'},
  {name: 'Bangladesh'},
  {name: 'Barbados'},
  {name: 'Belarus'},
  {name: 'Belgium'},
  {name: 'Belize'},
  {name: 'Benin'},
  {name: 'Bhutan'},
  {name: 'Bolivia'},
  {name: 'Bosnia and Herzegovina'},
  {name: 'Botswana'},
  {name: 'Brazil'},
  {name: 'Brunei Darussalam'},
  {name: 'Bulgaria'},
  {name: 'Burkina Faso'},
  {name: 'Burundi'},
  {name: 'Cambodia'},
  {name: 'Cameroon'},
  {name: 'Canada'},
  {name: 'Cayman Islands'},
  {name: 'Central African Republic'},
  {name: 'Chad'},
  {name: 'Chile'},
  {name: 'China'},
  {name: 'Colombia'},
  {name: 'Comoros'},
  {name: 'Congo'},
  {name: 'Congo, The Democratic Republic of the'},
  {name: 'Costa Rica'},
  {name: 'Croatia'},
  {name: 'Cuba'},
  {name: 'Cyprus'},
  {name: 'Czech Republic'},
  {name: 'Czechia'},
  {name: "Côte D'Ivoire"},
  {name: 'Denmark'},
  {name: 'Dominican Republic'},
  {name: 'Ecuador'},
  {name: 'Egypt'},
  {name: 'El Salvador'},
  {name: 'Equatorial Guinea'},
  {name: 'Estonia'},
  {name: 'Ethiopia'},
  {name: 'Faroe Islands'},
  {name: 'Federated States of Micronesia'},
  {name: 'Fiji'},
  {name: 'Finland'},
  {name: 'Former Serbia and Montenegro'},
  {name: 'Former Yugoslavia'},
  {name: 'France'},
  {name: 'French Guiana'},
  {name: 'Gabon'},
  {name: 'Gambia'},
  {name: 'Georgia'},
  {name: 'Germany'},
  {name: 'Ghana'},
  {name: 'Gibraltar'},
  {name: 'Greece'},
  {name: 'Greenland'},
  {name: 'Grenada'},
  {name: 'Guadeloupe'},
  {name: 'Guam'},
  {name: 'Guatemala'},
  {name: 'Guinea'},
  {name: 'Guinea-Bissau'},
  {name: 'Guyana'},
  {name: 'Haiti'},
  {name: 'Holy See (Vatican City State)'},
  {name: 'Honduras'},
  {name: 'Hong Kong'},
  {name: 'Hungary'},
  {name: 'Iceland'},
  {name: 'India'},
  {name: 'Indonesia'},
  {name: 'Iran, Islamic Republic of'},
  {name: 'Iraq'},
  {name: 'Ireland'},
  {name: 'Israel'},
  {name: 'Italy'},
  {name: 'Jamaica'},
  {name: 'Japan'},
  {name: 'Jersey'},
  {name: 'Jordan'},
  {name: 'Kazakhstan'},
  {name: 'Kenya'},
  {name: 'Korea, Republic of'},
  {name: 'Kosovo'},
  {name: 'Kuwait'},
  {name: 'Kyrgyzstan'},
  {name: "Lao People's Democratic Republic"},
  {name: 'Latvia'},
  {name: 'Lebanon'},
  {name: 'Lesotho'},
  {name: 'Liberia'},
  {name: 'Libyan Arab Jamahiriya'},
  {name: 'Liechtenstein'},
  {name: 'Lithuania'},
  {name: 'Luxembourg'},
  {name: 'Macedonia, The Former Yugoslav Republic of'},
  {name: 'Madagascar'},
  {name: 'Malawi'},
  {name: 'Malaysia'},
  {name: 'Mali'},
  {name: 'Malta'},
  {name: 'Martinique'},
  {name: 'Mauritius'},
  {name: 'Mexico'},
  {name: 'Moldova, Republic of'},
  {name: 'Mongolia'},
  {name: 'Montenegro'},
  {name: 'Morocco'},
  {name: 'Mozambique'},
  {name: 'Myanmar'},
  {name: 'Namibia'},
  {name: 'Nepal'},
  {name: 'Netherlands'},
  {name: 'New Zealand'},
  {name: 'Nicaragua'},
  {name: 'Niger'},
  {name: 'Nigeria'},
  {name: 'North Macedonia'},
  {name: 'Northern Mariana Islands'},
  {name: 'Norway'},
  {name: 'Oman'},
  {name: 'Pakistan'},
  {name: 'Palestinian Territories, Occupied'},
  {name: 'Palestinian Territory, occupied'},
  {name: 'Panama'},
  {name: 'Papua New Guinea'},
  {name: 'Paraguay'},
  {name: 'Peru'},
  {name: 'Philippines'},
  {name: 'Poland'},
  {name: 'Portugal'},
  {name: 'Puerto Rico'},
  {name: 'Qatar'},
  {name: 'Romania'},
  {name: 'Russian Federation'},
  {name: 'Rwanda'},
  {name: 'Réunion'},
  {name: 'Saint Kitts and Nevis'},
  {name: 'Samoa'},
  {name: 'Saudi Arabia'},
  {name: 'Senegal'},
  {name: 'Serbia'},
  {name: 'Sierra Leone'},
  {name: 'Singapore'},
  {name: 'Slovakia'},
  {name: 'Slovenia'},
  {name: 'Solomon Islands'},
  {name: 'Somalia'},
  {name: 'South Africa'},
  {name: 'Spain'},
  {name: 'Sri Lanka'},
  {name: 'Sudan'},
  {name: 'Suriname'},
  {name: 'Swaziland'},
  {name: 'Sweden'},
  {name: 'Switzerland'},
  {name: 'Syrian Arab Republic'},
  {name: 'Taiwan'},
  {name: 'Tajikistan'},
  {name: 'Tanzania'},
  {name: 'Thailand'},
  {name: 'Togo'},
  {name: 'Trinidad and Tobago'},
  {name: 'Tunisia'},
  {name: 'Turkey'},
  {name: 'Uganda'},
  {name: 'Ukraine'},
  {name: 'United Arab Emirates'},
  {name: 'United Kingdom'},
  {name: 'United States'},
  {name: 'Uruguay'},
  {name: 'Uzbekistan'},
  {name: 'Venezuela'},
  {name: 'Vietnam'},
  {name: 'Virgin Islands (U.S.)'},
  {name: 'Yemen'},
  {name: 'Zambia'},
  {name: 'Zimbabwe'},
]